--- 
- hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Install multiple packages
    yum: name={{item}} state=latest
    with_items:
    - git
    - httpd
    - docker
    - java
    - python
    - php
  - name: Start multple service
    service: name={{item}} state=started
    with_items:
    - httpd
    - docker
