---
- hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Install git
    yum: name=git state=latest
  - name: Install httpd
    yum: name=httpd state=latest
  - name: Install docker
    yum: name=docker state=latest
  - name: Install java 
    yum: name=java state=latest
  - name: Install mysql
    yum: name=mysql state=latest
    
##Use ansible-playbook playbook.yml --start-at-task="task name"
##Use ansible-playbook playbook.yml --step
