---
- hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: stop the container
    docker_container:
     name: jenkins_container
     state: stopped
  - name: remove the container
    docker_container:
     name: jenkins_container
     state: absent
